vars:
  keycloak-url: http://localhost:8081
server:
  port: 7000
eureka:
  client:
    fetch-register: true
    register-with-eureka: true
    defaultZone: http://localhost:8761/eureka
spring:
  config:
    import: optional:secrets.yml
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: module
          uri: lb://module
          predicates:
            - Path=/module/**
          filters:
            - RewritePath=/module/(?<path>.*), /$\{path}
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - TokenRelay=
        - id: keycloak
          uri: ${vars.keycloak-url}
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<path>.*), /$\{path}
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${vars.keycloak-url}/realms/realm
        registration:
          keycloak:
            client-id: ${secrets.client-id}
            authorization-grant-type: authorization_code
            client-secret: ${secrets.client-secret}
            provider: keycloak
            scope:
            - openid
            user-name-attribute: preferred_username