server:
  port: 7000
eureka:
  client:
    fetch-register: true
    register-with-eureka: true
    defaultZone: http://localhost:8761/eureka
spring:
  config:
    import: optional:secrets.properties
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: module
          uri: lb://module
          predicates:
            - Path=/module/**
          filters:
            - RewritePath=/module/(?<path>.*), /$\{path}
        - id: keycloak
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<path>.*), /$\{path}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs